[package]
name = "fletcher"
version = "0.0.2"
authors = ["Joseph Angelo <b.j.angelo@gmail.com>"]
description = "An implementation of Fletcher's Checksum algorithm in rust"
repository = "https://github.com/jbangelo/fletcher"
readme = "README.md"
keywords = ["fletcher", "checksum"]
categories = ["algorithms"]
license = "MIT"

[badges]
travis-ci = { repository = "jbangelo/fletcher", branch = "master" }

[dependencies]
